model:
    arch: fcn8s
data:
    dataset: pascal
    train_split: train90
    val_split: val5
    img_rows: 'same'
    img_cols: 'same'
    path: /content/drive/My Drive/datamining/pytorch-semseg/voc2012/VOCdevkit/VOC2012/
    sbd_path: /content/drive/My Drive/datamining/pytorch-semseg/sbd/benchmark_RELEASE/
training:
    train_iters: 5000
    batch_size: 1
    val_interval: 1000
    n_workers: 16
    print_interval: 100
    optimizer:
        name: 'sgd'
        lr: 1.0e-9
        weight_decay: 0.0005
        momentum: 0.99
    loss:
        name: 'cross_entropy'
        size_average: False
    lr_schedule:
    resume: fcn8s_pascal_best_model.pkl
